# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 251f8f67d9132ff25158792c3255bdcf3a16505b9be5fcb23970fd01eb4db6dddb51e1f3361cf865632a1a198633c2db0e289f342455b7ffc76dfa97cc81b4b3

test:
  secret_key_base: 4085f66ea478d8f1975725127c0a32041de41356fb2c54411e7965934bf8a77b4fc119cd630352edca18f40391be7f26da35280cea549334cdc523fadb4075ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
